Домашнее задание выполнено по теме Selenium. WebDriver
Pavel-T800/AQA25_onl pull request #1
Opened 2024-03-07 15:53 UTC by Pavel-T800

Сделал домашнее задание по теме Selenium. WebDriver. 
Написал тесты на проверку расчетов “Калькулятор ламината” и на проверку 'СКФ', а так же проверил рассчитанные результаты в рамках тестов: 'ByMedCalcTest' и 'LaminateCalcTest'

2024-03-10 22:03 UTC, wildpioneer requested changes

2024-03-10 22:03 UTC, wildpioneer commented on src/test/java/LaminateCalcTest.java
> +//      "Минимальная длина обрезка" и "Отступ от стен" оставлены с неизменными значениями,
В PR не надо оставлять закомментированный код

2024-03-10 22:03 UTC, wildpioneer commented on src/test/java/ByMedCalcTest.java
> +
Не стоит ставить пустые строки перед закрытием метода

2024-03-11 09:00 UTC, Pavel-T800 commented on src/test/java/LaminateCalcTest.java
> +//      "Минимальная длина обрезка" и "Отступ от стен" оставлены с неизменными значениями,
исправил в бранче Selenium

2024-03-11 09:00 UTC, Pavel-T800 commented on src/test/java/ByMedCalcTest.java
> +
исправил в бранче Selenium

2024-03-18 11:04 UTC, wildpioneer commented
Проверено

2024-03-18 11:04 UTC, closed without merging